# Generated by Django 4.2 on 2023-05-25 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0002_alter_ubicacionfisica_ubilocker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleentradamaterial',
            old_name='devEstado',
            new_name='detEstado',
        ),
        migrations.RemoveField(
            model_name='material',
            name='matUnidadMedida',
        ),
        migrations.AddField(
            model_name='detalleentradamaterial',
            name='detUnidadMedida',
            field=models.ForeignKey(db_comment='Hace referencia a la Unidad de Medida FK', null=True, on_delete=django.db.models.deletion.PROTECT, to='appGestionInventario.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='entradamaterial',
            name='entFechaHora',
            field=models.DateTimeField(db_comment='Fecha y hora que entregan los elementos', default=django.utils.timezone.now),
        ),
    ]
