# Generated by Django 4.2 on 2023-05-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0003_rename_devestado_detalleentradamaterial_detestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleentradamaterial',
            name='detUnidadMedida',
            field=models.ForeignKey(db_comment='Hace referencia a la Unidad de Medida FK', default=None, on_delete=django.db.models.deletion.PROTECT, to='appGestionInventario.unidadmedida'),
        ),
    ]
